# Generated by Django 5.2.1 on 2025-05-16 10:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('cod_fiscale', models.CharField(max_length=16, unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('lingua_preferita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Askos.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('cod_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('ruolo', models.CharField(choices=[('guida', 'Guida'), ('driver', 'Driver')], max_length=10)),
                ('lingue', models.ManyToManyField(related_name='staff_members', to='Askos.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('durata', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('driver', models.ManyToManyField(blank=True, limit_choices_to={'ruolo': 'driver'}, related_name='tour_driver', to='Askos.staff')),
                ('guide', models.ManyToManyField(blank=True, limit_choices_to={'ruolo': 'guida'}, related_name='tour_guide', to='Askos.staff')),
                ('lingua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tour', to='Askos.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prenotazione', models.DateField(auto_now_add=True)),
                ('num_partecipanti', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='Askos.cliente')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prenotazioni', to='Askos.tour')),
            ],
        ),
        migrations.CreateModel(
            name='Recensione',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.PositiveIntegerField()),
                ('commento', models.TextField(blank=True)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Askos.cliente')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Askos.tour')),
            ],
            options={
                'unique_together': {('cliente', 'tour')},
            },
        ),
    ]
