# Generated by Django 5.2.1 on 2025-05-13 19:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Guida',
            fields=[
                ('cod_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('eta', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('lingue', models.ManyToManyField(related_name='guide', to='Askos.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_fiscale', models.CharField(max_length=16, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('cognome', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('lingua_preferita', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Askos.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id_tour', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('durata', models.CharField(max_length=50)),
                ('prezzo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('guida', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Askos.guida')),
                ('lingua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Askos.lingua')),
            ],
        ),
        migrations.CreateModel(
            name='Prenotazione',
            fields=[
                ('id_prenotazione', models.AutoField(primary_key=True, serialize=False)),
                ('data_prenotazione', models.DateField(auto_now_add=True)),
                ('num_partecipanti', models.PositiveIntegerField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Askos.cliente')),
                ('tour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Askos.tour')),
            ],
        ),
    ]
