# Generated by Django 5.2.1 on 2025-05-22 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Askos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='staff_assegnato',
            field=models.ManyToManyField(related_name='tour_assegnati', to='Askos.staff'),
        ),
    ]
